In [2]:
import numpy as np

# 1. Creating 3 arrays(1d, 2d, 3d)

In [11]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [12]:
a2 = np.array([[1.1, 2.2, 3.3],
              [4.4, 5.5, 6.6]])
a2

array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6]])

In [13]:
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],

               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3
               

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## 2. Finding details like shape, size, type & dimension

In [18]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [19]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [20]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [21]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [22]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

# 3. importing pandas and creating a DF

In [27]:
import pandas as pd

panda_df = pd.DataFrame(a1)
panda_df

0
0  1
1  2
2  3

# 4. Creating an array of diff shapes

In [29]:
# shape(10, 2) with ones

array_ones = np.ones((10, 2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
# shape(7, 2, 3) with zeros

array_zeros = np.zeros((7, 2, 3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
# range(0:100) with step 3

range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [33]:
# random array (0:10) with size (7, 2)

random_array = np.random.randint(10, size=(7,2))
random_array

array([[2, 3],
       [3, 9],
       [3, 1],
       [8, 1],
       [6, 5],
       [1, 8],
       [0, 9]], dtype=int32)

In [37]:
# random array floats (0:1) with shape (3, 5)
random_array_flt = np.random.rand(3,5)
random_array_flt


array([[0.78094989, 0.45979424, 0.33465206, 0.51241954, 0.51823797],
       [0.03644205, 0.48576466, 0.37699342, 0.1598711 , 0.99632841],
       [0.94815172, 0.07855315, 0.91644366, 0.28268154, 0.10649644]])

In [38]:
# random number using seed
np.random.seed(42)
random_array_seed = np.random.randint(10, size=(4,6))
random_array_seed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [39]:
random_array_seed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [40]:
# Creatimg random numbers and saving to variable

random_numbers = np.random.randint(1, 10, size=(3, 7))
random_numbers

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]], dtype=int32)

In [46]:
# Finding unique numbers
np.unique(random_numbers)

array([1, 2, 3, 4, 5, 7, 9], dtype=int32)

In [47]:
# displaying numbers using Index
random_numbers[0]

array([9, 1, 3, 7, 4, 9, 3], dtype=int32)

In [48]:
# First 2 rows of latest array using slicing 
random_numbers[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [49]:
# First two values of first two rows

random_numbers[:2, :2]

array([[9, 1],
       [5, 3]], dtype=int32)

In [51]:
# Create a random array of num bw o:10 and an array on ones size (3, 5)

random_array_1 = np.random.randint(10, size=(3, 5))
random_array_ones = np.ones((3,5))

In [52]:
random_array_1, random_array_ones

(array([[9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]], dtype=int32),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [54]:
random_total = random_array_1 + random_array_ones
random_total

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [59]:
random_another_ones = np.ones((5, 3))
random_another_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
random_add = random_another_ones + random_total.T

In [63]:
random_add

array([[11.,  8.,  6.],
       [ 3., 10.,  9.],
       [11.,  9., 11.],
       [ 5.,  6., 10.],
       [ 9.,  3., 10.]])

In [64]:
random_array_ones = np.ones((3, 5))
random_array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
random_subtract = random_add - random_array_ones.T
random_subtract

array([[10.,  7.,  5.],
       [ 2.,  9.,  8.],
       [10.,  8., 10.],
       [ 4.,  5.,  9.],
       [ 8.,  2.,  9.]])

In [68]:
random_multiply = random_array_ones * random_subtract.T
random_multiply

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [69]:
random_multiply ** 2

array([[100.,   4., 100.,  16.,  64.],
       [ 49.,  81.,  64.,  25.,   4.],
       [ 25.,  64., 100.,  81.,  81.]])

In [70]:
np.square(random_multiply)

array([[100.,   4., 100.,  16.,  64.],
       [ 49.,  81.,  64.,  25.,   4.],
       [ 25.,  64., 100.,  81.,  81.]])

In [71]:
np.mean(random_multiply)

np.float64(7.066666666666666)

In [73]:
np.max(random_multiply), np.min(random_multiply)

(np.float64(10.0), np.float64(2.0))

In [74]:
np.std(random_multiply)

np.float64(2.6948510575210314)

In [75]:
np.sqrt(7.25)

np.float64(2.692582403567252)

In [76]:
np.var(random_multiply)

np.float64(7.262222222222222)

# 5. Reshaping and transposing the arrays

In [77]:
random_multiply.reshape(3, 5, 1)

array([[[10.],
        [ 2.],
        [10.],
        [ 4.],
        [ 8.]],

       [[ 7.],
        [ 9.],
        [ 8.],
        [ 5.],
        [ 2.]],

       [[ 5.],
        [ 8.],
        [10.],
        [ 9.],
        [ 9.]]])

In [78]:
random_multiply

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [79]:
random_multiply.reshape(3, 5, 1). T

array([[[10.,  7.,  5.],
        [ 2.,  9.,  8.],
        [10.,  8., 10.],
        [ 4.,  5.,  9.],
        [ 8.,  2.,  9.]]])

In [81]:
#  Creating two arrays of random integers

a4 = np.random.randint(10, size=(3,3))
a5 = np.random.randint(10, size=(3, 2))

In [82]:
a4, a5

(array([[0, 7, 2],
        [2, 0, 4],
        [9, 6, 9]], dtype=int32),
 array([[8, 6],
        [8, 7],
        [1, 0]], dtype=int32))

In [83]:
dot1 = np.dot(a4, a5)
dot1

array([[ 58,  49],
       [ 20,  12],
       [129,  96]], dtype=int32)

In [88]:
a6 = np.random.randint(10, size=(4,3))
a7 = np.random.randint(10, size=(4,3))
a6, a7

(array([[3, 4, 6],
        [6, 3, 6],
        [2, 5, 1],
        [9, 8, 4]], dtype=int32),
 array([[5, 3, 9],
        [6, 8, 6],
        [0, 0, 8],
        [8, 3, 8]], dtype=int32))

In [89]:
dot2 = np.dot(a6, a7.T)

In [90]:
dot2

array([[ 81,  86,  48,  84],
       [ 93,  96,  48, 105],
       [ 34,  58,   8,  39],
       [105, 142,  32, 128]], dtype=int32)

#  6. Comparision of arrays

In [92]:
a8 = np.random.randint(10, size=(3,3))
a9 = np.random.randint(10, size=(3,3))

a8, a9


(array([[2, 6, 5],
        [7, 8, 4],
        [0, 2, 9]], dtype=int32),
 array([[7, 5, 7],
        [8, 3, 0],
        [0, 9, 3]], dtype=int32))

In [93]:
a8 > a9

array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])

In [95]:
a8 >= a9

array([[False,  True, False],
       [False,  True,  True],
       [ True, False,  True]])

In [96]:
a8 > 7

array([[False, False, False],
       [False,  True, False],
       [False, False,  True]])

In [97]:
a8 == a9

array([[False, False, False],
       [False, False, False],
       [ True, False, False]])

In [98]:
np.sort(a8)

array([[2, 5, 6],
       [4, 7, 8],
       [0, 2, 9]], dtype=int32)

In [99]:
a8

array([[2, 6, 5],
       [7, 8, 4],
       [0, 2, 9]], dtype=int32)

In [100]:
np.argsort(a8)

array([[0, 2, 1],
       [2, 0, 1],
       [0, 1, 2]])

In [101]:
np.argmax(a8)

np.int64(8)

In [102]:
np.argmin(a9)

np.int64(5)

In [103]:
np.argmax(a8, axis=1)

array([1, 1, 2])

In [104]:
np.argmin(a8, axis=1)

array([0, 2, 0])